apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{.SpecialResource.Name}}
  name: {{.SpecialResource.Name}}
spec: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.SpecialResource.Name}}-buildah-helper
data:
  buildah-helper.sh: |-
    #!/bin/bash -x 

    CNT=
    MNT=

    MOUNT_MACHINE_OS_CONTENT() { export MOC=$(buildah --authfile /var/lib/kubelet/config.json  --storage-driver vfs from {{.OSImageURL}}); export MOCMNT=$(buildah --storage-driver vfs mount $MOC); }
    UMOUNT_MACHINE_OS_CONTENT() { buildah --storage-driver vfs umount $MOC;  }


    FROM() { export CNT=$(buildah --storage-driver vfs from $1); }

    MOUNT() { export MNT=$(buildah --storage-driver vfs mount $CNT); }
    UMOUNT() { buildah --storage-driver vfs umount $CNT; }

    ENV() { buildah config --env $@; }
    RUN() { buildah --storage-driver vfs --isolation chroot run --user 0 $CNT -- $@; }
    RUNV() { buildah --storage-driver vfs --isolation chroot run --volume /etc/pki/entitlement-host:/etc/pki/entitlement:z --volume ${MOCMNT}:/extensions:z --user 0 $CNT -- $@; }
    COPY() { buildah --storage-driver vfs copy $CNT $@; }
    COMMIT() { buildah --storage-driver vfs commit $CNT $1; }
    ENTRYPOINT() { buildah config --entrypoint $1 $CNT; }
    WORKINGDIR() { buildah --storage-driver vfs config --workingdir $1 $CNT; }
    PUSH() { buildah --storage-driver vfs push --tls-verify=false --authfile /root/.dockercfg  $@; }


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.SpecialResource.Name}}-install-dependencies
data:
  install-dependencies.sh: |-
    #!/bin/bash -x
    
    UNAME=$(uname -r)

    # First update the base container to latest versions of everything
    yum update -y --enablerepo=rhel-8-for-x86_64-baseos-eus-rpms --releasever={{.OperatingSystemDecimal}}

    # Additional packages that are mandatory for driver-containers
    yum -y --setopt=install_weak_deps=False --best install elfutils-libelf-devel kmod


    # Enable EUS and try to install kernel-devel and kernel-headers
    yum -y --enablerepo=rhel-8-for-x86_64-baseos-eus-rpms --releasever={{.OperatingSystemDecimal}} \
      --setopt=install_weak_deps=False --best install \
      kernel-devel-${UNAME} kernel-headers-${UNAME} kernel-core-${UNAME}
    
    if [ $? -eq 0 ]; then
      echo "EUS - kernel-devel-${UNAME} kernel-headers-${UNAME} kernel-core-${UNAME} installed"
      exit 0
    fi

    # If EUS fails get kernel-devel and kernel-headers from machine-os-content
    echo "EUS FAILED - installing from machine-os-content"

    KERNEL_DEVEL=$(find /extensions -name kernel-devel-${UNAME}.rpm -exec ls {} \; | tail -n1)
    KERNEL_HEADERS=$(find /extensions -name kernel-headers-${UNAME}.rpm -exec ls {} \; | tail -n1) 
    KERNEL_CORE=$(find /extensions -name kernel-core-${UNAME}.rpm -exec ls {} \; | tail -n1)
       
    yum -y --setopt=install_weak_deps=False --best install $KERNEL_DEVEL
    yum -y --setopt=install_weak_deps=False --best install $KERNEL_HEADERS
    # We do not need dependencies for kernel-core just install the RPM    
    rpm -ivh --nodeps $KERNEL_CORE

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.SpecialResource.Name}}-entrypoint
data:
  entrypoint.sh: |-
    #!/bin/bash -x 
    set -e
    cd /tmp

    yum -y install buildah git make --setopt=install_weak_deps=False

    git clone {{.SpecialResource.Spec.DriverContainer.Source.Git.Uri}}

    source /bin/buildah-helper.sh

    UNAME=$(uname -r)
    SCRIPT_NAME=install-dependencies.sh
    TAG={{.SpecialResource.Namespace}}/{{.SpecialResource.Name}}:v${UNAME}

   
    # --------- Container instructions START ----------------------------------
 
    MOUNT_MACHINE_OS_CONTENT

    FROM registry.access.redhat.com/ubi8/ubi

    WORKINGDIR /tmp
 
    COPY /bin/${SCRIPT_NAME} .
    RUNV bash -c $(pwd)/${SCRIPT_NAME}
 
    # Install directly into the chroot, this way we do not have to install
    # additinoal packages like git into the container to install from a git repo
    # The deps are resolved by the outer image. 
    MOUNT
    cd kmods-via-containers
    make install DESTDIR=${MNT}/usr/local CONFDIR=${MNT}/etc/
    UMOUNT

    COMMIT ${TAG}
    PUSH   ${TAG} image-registry.openshift-image-registry.svc:5000/${TAG}

    UMOUNT_MACHINE_OS_CONTENT

    # --------- Container instructions END ------------------------------------
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{.SpecialResource.Name}}
  name: {{.SpecialResource.Name}}
spec:
  serviceAccount: builder
  serviceAccountName: builder
  restartPolicy: OnFailure
  containers:
  - name: {{.SpecialResource.Name}}-ctr
    image: "registry.access.redhat.com/ubi8:latest"
    env: 
    - name: HTTP_PROXY
      value: {{.Proxy.HttpProxy}}
    - name: HTTPS_PROXY
      value: {{.Proxy.HttpsProxy}}
    - name: NO_PROXY
      value: {{.Proxy.NoProxy}}
    command: ["/bin/entrypoint.sh"]
    securityContext:
      seLinuxOptions:
        type: spc_t
    volumeMounts:
        - name: entrypoint
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        - name: install-dependencies
          mountPath: /bin/install-dependencies.sh
          readOnly: true
          subPath: install-dependencies.sh
        - name: buildah-helper
          mountPath: /bin/buildah-helper.sh
          readOnly: true
          subPath: buildah-helper.sh
        - name: authfile
          mountPath: /var/lib/kubelet
          readOnly: true
        - name: dockercfg
          mountPath: /root
          readOnly: true
  volumes:
    - name: dockercfg
      secret:
        secretName: {{.PushSecretName}}
    - name: authfile
      hostPath:
        path: /var/lib/kubelet
    - name: entrypoint
      configMap:
        defaultMode: 0700
        name: {{.SpecialResource.Name}}-entrypoint
    - name: install-dependencies
      configMap:
        defaultMode: 0700
        name: {{.SpecialResource.Name}}-install-dependencies
    - name: buildah-helper
      configMap:
        defaultMode: 0700
        name: {{.SpecialResource.Name}}-buildah-helper
