apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kube-system
stringData:
  {{(index .SpecialResource.Spec.Environment 0).Key}}: "{{(index .SpecialResource.Spec.Environment 0).Value}}"
  {{(index .SpecialResource.Spec.Environment 1).Key}}: "{{(index .SpecialResource.Spec.Environment 1).Value}}"
  