# permissions for end users to view specialresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: specialresource-viewer-role
rules:
- apiGroups:
  - sro.openshift.io
  resources:
  - specialresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sro.openshift.io
  resources:
  - specialresources/status
  verbs:
  - get
