apiVersion: sro.openshift.io/v1alpha1
kind: SpecialResource
metadata:
  name: nvidia-gpu
  namespace: openshift-sro
spec:
  driverContainer:
    source:
      git:
        ref: "master"
        uri: "https://gitlab.com/nvidia/driver.git"
    buildArgs: 
    - name: "DRIVER_VERSION"
      value: "440.64.00"
  node:
    selector: "feature.node.kubernetes.io/pci-10de.present"
    
