apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - 0000-driver-container-base-build.yaml
  name: driver-container-base
  
namespace: driver-container-base
