apiVersion: sro.openshift.io/v1alpha1
kind: SpecialResource
metadata:
  name: mlnx-rdma-shared-mofed
  namespace: REPLACE_NAMESPACE
spec:
  driverContainer:
    source:
      git:
        ref: "master"
        uri: https://github.com/openshift-psap/mofed-driver-container.git
    buildArgs:
    - name: "DRIVER_VERSION"
      value: "4.7-1.0.0.1"
    runArgs:
    - name: "LINK_TYPE_P1" # 1st Port
      value: "2"  #Ethernet
    - name: "LINK_TYPE_P2" # 2nd Port
      value: "2"  #Ethernet
  node:
    selector: "feature.node.kubernetes.io/pci-10de.present"
  