apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{.SpecialResource.Name}}-{{.GroupName.DriverContainer}}
  name: {{.SpecialResource.Name}}-{{.GroupName.DriverContainer}}
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{.SpecialResource.Name}}-{{.GroupName.DriverBuild}} 
  name: {{.SpecialResource.Name}}-{{.GroupName.DriverBuild}}
  annotations:
    specialresource.openshift.io/wait: "true"
    specialresource.openshift.io/driver-container-vendor: {{.SpecialResource.Spec.Node.Selector}}    
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
    {{.SpecialResource.Spec.Node.Selector}}: "true"
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    git:
      ref: master
      uri: {{.SpecialResource.Spec.DriverContainer.Source.Git.Uri}}
    contextDir: {{.OperatingSystemMajorMinor}}
    type: Git
  strategy:
    dockerStrategy:
      buildArgs:
        - name: "{{ (index .SpecialResource.Spec.DriverContainer.BuildArgs 1).name }}"
          value: "{{ (index .SpecialResource.Spec.DriverContainer.BuildArgs 1).name }}"
  output:
    to:
      kind: ImageStreamTag
      name: {{.SpecialResource.Name}}-{{.GroupName.DriverContainer}}:v{{.KernelVersion}}
